pwa/src/components/requiredStar/RequiredStar.module.css
pwa/src/components/requiredStar/RequiredStar.tsx
pwa/src/templates/templateParts/actionsForm/CreateActionFormTemplate.tsx
pwa/src/templates/templateParts/actionsForm/EditActionFormTemplate.tsx
pwa/src/templates/templateParts/collectionsForm/CreateCollectionFormTemplate.tsx
pwa/src/templates/templateParts/collectionsForm/EditCollectionFormTemplate.tsx
pwa/src/templates/templateParts/cronjobsForm/CreateCronjobsFormTemplate.tsx
pwa/src/templates/templateParts/cronjobsForm/EditCronjobFormTemplate.tsx
pwa/src/templates/templateParts/endpointsForm/CreateEndpointsFormTemplate.tsx
pwa/src/templates/templateParts/endpointsForm/EditEndpointsFormTemplate.tsx
pwa/src/templates/templateParts/loginForm/LoginFormTemplate.tsx
pwa/src/templates/templateParts/objectsFormTemplate/CreateObjectFormTemplate.tsx
pwa/src/templates/templateParts/pluginsForm/CreatePluginFormTemplate.tsx
pwa/src/templates/templateParts/pluginsForm/EditPluginFormTemplate.tsx
pwa/src/templates/templateParts/propertyForm/CreatePropertyFormTemplate.tsx
pwa/src/templates/templateParts/propertyForm/EditPropertyFormTemplate.tsx
pwa/src/templates/templateParts/schemaForm/SchemaFormTemplate.tsx
pwa/src/templates/templateParts/schemasForm/CreateSchemasFormTemplate.tsx
pwa/src/templates/templateParts/schemasForm/EditSchemasFormTemplate.tsx
pwa/src/templates/templateParts/sourcesForm/CreateSourceFormTemplate.tsx
pwa/src/templates/templateParts/sourcesForm/EditSourcesFormTemplate.tsx
pwa/src/templates/templateParts/sourcesForm/SourcesAuthFormTemplate.tsx
pwa/src/templates/templateParts/userGroupsForm/CreateUserGroupFormTemplate.tsx
pwa/src/templates/templateParts/userGroupsForm/EditUserGroupFormTemplate.tsx

Reverts ConductionNL/gateway-ui#88

Revert "feature/KISS-284/required-fields-have-star"

---

pwa/package-lock.json
pwa/package.json
pwa/src/services/auth.tsx
pwa/src/templates/sourcesDetailTemplate/SourcesDetailTemplate.tsx
pwa/src/templates/templateParts/actionsForm/CreateActionFormTemplate.tsx
pwa/src/templates/templateParts/actionsForm/EditActionFormTemplate.tsx
pwa/src/templates/templateParts/applicationsForm/ApplicationsFormTemplate.tsx
pwa/src/templates/templateParts/authenticationForm/AuthenticationFormTemplate.tsx
pwa/src/templates/templateParts/cronjobsForm/CreateCronjobsFormTemplate.tsx
pwa/src/templates/templateParts/cronjobsForm/EditCronjobFormTemplate.tsx
pwa/src/templates/templateParts/endpointsForm/CreateEndpointsFormTemplate.tsx
pwa/src/templates/templateParts/endpointsForm/EditEndpointsFormTemplate.tsx
pwa/src/templates/templateParts/objectsFormTemplate/CreateObjectFormTemplate.tsx
pwa/src/templates/templateParts/propertyForm/CreatePropertyFormTemplate.tsx
pwa/src/templates/templateParts/propertyForm/EditPropertyFormTemplate.tsx
pwa/src/templates/templateParts/sourcesForm/CreateSourceFormTemplate.tsx
pwa/src/templates/templateParts/sourcesForm/EditSourcesFormTemplate.tsx
pwa/src/templates/templateParts/syncForm/CreateSyncFormTemplate.tsx
pwa/src/templates/templateParts/syncForm/EditSyncFormTemplate.tsx
pwa/src/templates/templateParts/userForm/UserFormTemplate.tsx

Removes all (now redundant) `@ts-ignore` statements.

Bugfix/oc 447/ts errors

---

pwa/src/styling/design-tokens/component-overrides.css
pwa/src/templates/schemasTemplate/SchemasTemplate.module.css
pwa/src/templates/schemasTemplate/SchemasTemplate.tsx

See commit messages and issue for context.

Feature/oc 443/edit schema button

---

pwa/package-lock.json
pwa/package.json

See JIRA issue for more information, changes in conduction/components have been merged and published.

IMPLEMENT conduction/components 2.1.7 with new Select elements

---

pwa/src/apiService/resources/schema.ts
pwa/src/hooks/action.ts
pwa/src/hooks/application.ts
pwa/src/hooks/attribute.ts
pwa/src/hooks/authentication.ts
pwa/src/hooks/callLog.ts
pwa/src/hooks/collection.ts
pwa/src/hooks/cronjob.ts
pwa/src/hooks/dashboardCards.ts
pwa/src/hooks/endpoint.ts
pwa/src/hooks/log.ts
pwa/src/hooks/me.ts
pwa/src/hooks/object.ts
pwa/src/hooks/organization.ts
pwa/src/hooks/plugin.ts
pwa/src/hooks/schema.ts
pwa/src/hooks/securityGroup.ts
pwa/src/hooks/source.ts
pwa/src/hooks/synchronization.ts
pwa/src/hooks/user.ts

This pull requests rewrites all `throw new Error(...)` to `console.warn`.

REFACTOR throws to warnings

---

pwa/src/context/isLoading.ts
pwa/src/hooks/dashboardCards.ts
pwa/src/hooks/source.ts
pwa/src/hooks/synchronization.ts
pwa/src/hooks/useDashboardCard.ts
pwa/src/templates/schemasDetailTemplate/SchemasDetailTemplate.tsx
pwa/src/templates/sourcesDetailTemplate/SourcesDetailTemplate.tsx
pwa/src/templates/templateParts/actionsForm/EditActionFormTemplate.tsx
pwa/src/templates/templateParts/authenticationForm/EditAuthenticationFormTemplate.tsx
pwa/src/templates/templateParts/collectionsForm/EditCollectionFormTemplate.tsx
pwa/src/templates/templateParts/cronjobsForm/EditCronjobFormTemplate.tsx
pwa/src/templates/templateParts/endpointsForm/EditEndpointsFormTemplate.tsx
pwa/src/templates/templateParts/objectsFormTemplate/EditObjectFormTemplate.tsx
pwa/src/templates/templateParts/organizationsForm/OrganizationForm.tsx
pwa/src/templates/templateParts/sourcesForm/EditSourcesFormTemplate.tsx
pwa/src/templates/templateParts/userForm/EditUserFormTemplate.tsx

This pull request:
- Refactors isLoading context (removes dashboard loading states);
- Refactors useDashboardCards hook, to include and export its own loading state;
- Refactors all useDashboardCard implementations, to grab the loading state and implement it accordingly;
- Renames all addOrRemove to toggle.

Feature/oc 454/dashboard loading

---

pwa/src/templates/templateParts/actionsForm/EditActionFormTemplate.tsx
pwa/src/templates/templateParts/cronjobsForm/EditCronjobFormTemplate.tsx
pwa/src/templates/templateParts/endpointsForm/EditEndpointsFormTemplate.tsx
pwa/src/templates/templateParts/schemasForm/CreateSchemasFormTemplate.tsx
pwa/src/templates/templateParts/schemasForm/EditSchemasFormTemplate.tsx
pwa/src/templates/templateParts/sourcesForm/EditSourcesFormTemplate.tsx
pwa/src/templates/templateParts/sourcesForm/SourcesAuthFormTemplate.tsx

Finalisation of OC-464, 461, 460, 457, 456, 454.

Feature/oc 454/loading state

---

pwa/src/context/isLoading.ts
pwa/src/templates/applicationsDetailTemplate/CreateApplicationTemplate.tsx
pwa/src/templates/applicationsDetailTemplate/EditApplicationsTemplate.tsx
pwa/src/templates/gatewayDetailTemplate/GatewayDetailTemplate.tsx
pwa/src/templates/templateParts/applicationsForm/ApplicationsFormTemplate.module.css
pwa/src/templates/templateParts/applicationsForm/ApplicationsFormTemplate.tsx

This pull request includes:
- Refactoring of application loading states to context;
- Refactoring of saving applications to `id` format.

REFACTOR Application Form states

---

pwa/src/templates/cronjobsTemplate/CronjobsTemplate.module.css
pwa/src/templates/cronjobsTemplate/CronjobsTemplate.tsx
pwa/src/templates/endpointsTemplate/EndpointsTemplate.module.css
pwa/src/templates/endpointsTemplate/EndpointsTemplate.tsx

This pull request adds a default color for unknown status.

REFACTOR cronjob en source status

---

pwa/src/apiService/resources/action.ts
pwa/src/apiService/resources/application.ts
pwa/src/apiService/resources/cronjob.ts
pwa/src/apiService/resources/endpoint.ts
pwa/src/apiService/resources/organization.ts
pwa/src/apiService/resources/schema.ts
pwa/src/apiService/resources/user.ts
pwa/src/hooks/action.ts
pwa/src/hooks/application.ts
pwa/src/hooks/cronjob.ts
pwa/src/hooks/endpoint.ts
pwa/src/hooks/organization.ts
pwa/src/hooks/schema.ts
pwa/src/hooks/user.ts
pwa/src/layout/Layout.tsx
pwa/src/templates/logsDetailTemplate/LogsDetailTemplate.tsx
pwa/src/templates/templateParts/logFilters/LogFiltersTemplate.tsx

This pull request includes:
- Addition of getAllSelectOptions hook for resources;
- Pre-filling LogsFilter form with logs context;
- Addition of filter functionality on log detail page.

Feature/oc 534/filter callback

---

pwa/src/context/logs.ts
pwa/src/templates/logsDetailTemplate/LogsDetailTemplate.tsx
pwa/src/templates/templateParts/logFilters/LogFiltersTemplate.module.css
pwa/src/templates/templateParts/logFilters/LogFiltersTemplate.tsx

This pull request adds ability to filter on sessions and processes.

Feature/oc 554/process session filters

---

pwa/package-lock.json
pwa/package.json
pwa/src/templates/templateParts/endpointsForm/EndpointFormTemplate.tsx
pwa/src/templates/templateParts/endpointsForm/EndpointsFormTemplate.module.css
pwa/src/templates/templateParts/propertyForm/CreatePropertyFormTemplate.tsx
pwa/src/templates/templateParts/propertyForm/EditPropertyFormTemplate.tsx

Refactors checkboxes to remove shape-rendering errors.

Bugfix/oc 556/checkbox warnings

---

pwa/src/components/bulkActionButton/BulkActionButton.tsx
pwa/src/hooks/source.ts
pwa/src/hooks/useBulkSelect.tsx
pwa/src/templates/actionsTemplate/ActionsTemplate.module.css
pwa/src/templates/actionsTemplate/ActionsTemplate.tsx
pwa/src/templates/applicationsTemplate/ApplicationsTemplate.tsx
pwa/src/templates/authenticationsTemplate/AuthenticationsTemplate.tsx
pwa/src/templates/collectionTemplate/CollectionsTemplate.tsx
pwa/src/templates/cronjobsTemplate/CronjobsTemplate.tsx
pwa/src/templates/endpointsTemplate/EndpointsTemplate.tsx
pwa/src/templates/mappingTemplate/MappingsTemplate.tsx
pwa/src/templates/objectTemplate/ObjectTemplate.tsx
pwa/src/templates/schemasTemplate/SchemasTemplate.tsx
pwa/src/templates/securityGroupsTemplate/SecurityGroupsTemplate.tsx
pwa/src/templates/sourcesTemplate/SourcesTemplate.tsx
pwa/src/templates/usersTemplate/UsersTemplate.tsx

Feature/oc 597/bulk delete implementation

---

pwa/src/components/button/Button.module.css
pwa/src/components/button/Button.tsx
pwa/src/components/paginate/Paginate.tsx
pwa/src/context/logs.ts
pwa/src/styling/design-tokens/gateway-ui-design-tokens.css
pwa/src/templates/templateParts/logsTable/LogsTableTemplate.module.css
pwa/src/templates/templateParts/logsTable/LogsTableTemplate.tsx

Check commit messages for contents.

Feature/oc 635/logs sorting

---

pwa/src/components/bulkActionButton/BulkActionButton.tsx
pwa/src/hooks/object.ts
pwa/src/hooks/useBulkSelect.tsx
pwa/src/templates/templateParts/formSaveButton/FormSaveButton.tsx
pwa/static/env.js

- Ups on blur timeout, due to the dropdown sometimes being removed before the click is registered;
- Removes onChange on useBulkSelect checkbox, and makes it readOnly, due to it being controlled elsewhere (this was registering the items twice which was messing up the count).

Bugfix/oc 638/bulk actions issues

---

pwa/package-lock.json
pwa/package.json
pwa/src/components/paginationLocationIndicatorComponent/PaginationLocationIndicatorComponent.tsx
pwa/src/context/logs.ts
pwa/src/services/validateJSON.ts
pwa/src/templates/EndpointsDetailTemplate/EndpointDetailsTemplate.tsx
pwa/src/templates/actionsDetailTemplate/ActionsDetailsTemplate.tsx
pwa/src/templates/collectionDetailsTemplate/CollectionsDetailsTemplate.tsx
pwa/src/templates/cronjobsDetailTemplate/CronjobsDetailsTemplate.tsx
pwa/src/templates/logsTemplate/LogsTemplate.module.css
pwa/src/templates/logsTemplate/LogsTemplate.tsx
pwa/src/templates/objectDetailTemplate/ObjectDetailTemplate.tsx
pwa/src/templates/schemasDetailTemplate/SchemasDetailTemplate.tsx
pwa/src/templates/sourcesDetailTemplate/SourcesDetailTemplate.tsx
pwa/src/templates/templateParts/logFilters/LogFiltersTemplate.module.css
pwa/src/templates/templateParts/logFilters/LogFiltersTemplate.tsx
pwa/src/templates/templateParts/logsTable/LogsTableTemplate.tsx
pwa/src/templates/templateParts/organizationsForm/EditOrganizationTemplate.tsx
pwa/src/templates/templateParts/userForm/EditUserTemplate.tsx

This pull request:
- Implements filtering on id, start datetime and end datetime;
- Refactors pagination indicator format and fixes wrong data being passed;

Feature/oc 701/logs filtering refactor

---

pwa/src/hooks/mapping.ts
pwa/src/templates/actionsTemplate/ActionsTemplate.tsx
pwa/src/templates/collectionTemplate/CollectionsTemplate.tsx
pwa/src/templates/cronjobsTemplate/CronjobsTemplate.tsx
pwa/src/templates/endpointsTemplate/EndpointsTemplate.tsx
pwa/src/templates/mappingTemplate/MappingsTemplate.tsx
pwa/src/templates/sourcesTemplate/SourcesTemplate.tsx

This pull request adds ActionButtons to all tables (except for the ones in settings)

ADD ActionButtons to all top-level resources

---

pwa/src/apiService/resources/object.ts
pwa/src/apiService/resources/schema.ts
pwa/src/components/actionButton/ActionButton.tsx
pwa/src/data/downloadTypes.ts
pwa/src/hooks/object.ts
pwa/src/hooks/schema.ts
pwa/src/services/downloadBlob.ts
pwa/src/templates/schemasDetailTemplate/SchemasDetailTemplate.tsx
pwa/src/templates/schemasTemplate/SchemasTemplate.tsx
pwa/src/templates/templateParts/objectsFormTemplate/EditObjectFormTemplate.tsx
pwa/src/templates/templateParts/objectsTable/ObjectsTable.tsx

Reverts ConductionNL/gateway-ui#339

Revert "feature/BEL-17/Schema-download"

---

pwa/src/templates/templateParts/importResourceActions/ImportResourceActionsTemplate.tsx
pwa/src/templates/templateParts/importResourceActions/formSteps/fileSelect/FormStepFileSelect.tsx
pwa/src/templates/templateParts/importResourceActions/formSteps/optionsSelect/FormStepOptionsSelect.tsx

Reverts ConductionNL/gateway-ui#341

Revert "Revert "feature/BEL-16/CSV-support""

---

pwa/src/apiService/resources/object.ts
pwa/src/apiService/resources/schema.ts
pwa/src/components/actionButton/ActionButton.tsx
pwa/src/data/downloadTypes.ts
pwa/src/hooks/object.ts
pwa/src/hooks/schema.ts
pwa/src/services/downloadBlob.ts
pwa/src/templates/schemasDetailTemplate/SchemasDetailTemplate.tsx
pwa/src/templates/schemasTemplate/SchemasTemplate.tsx
pwa/src/templates/templateParts/objectsFormTemplate/EditObjectFormTemplate.tsx
pwa/src/templates/templateParts/objectsTable/ObjectsTable.tsx

Reverts ConductionNL/gateway-ui#340

Revert "Revert "feature/BEL-17/Schema-download""
